name: ds_solucoes
description: "Sistema de gestão da DS Soluções."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pdf: ^3.13.0
  printing: ^5.15.0
  image_picker: ^1.1.2
  firebase_core: ^4.13.0
  cloud_firestore: ^6.8.0
  firebase_storage: ^13.4.6
  firebase_auth: ^6.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png