// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD50RuW_UvWawBcWYusCVS4_nGwwlZpnME',
    appId: '1:321468437653:web:8d587eecca1c042defb79c',
    messagingSenderId: '321468437653',
    projectId: 'ds-solucoes-67319',
    authDomain: 'ds-solucoes-67319.firebaseapp.com',
    storageBucket: 'ds-solucoes-67319.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOMVxLNzhPlIbChzeVNy2DgLrG9KcCHHk',
    appId: '1:321468437653:android:21d6686d1cbc9a07efb79c',
    messagingSenderId: '321468437653',
    projectId: 'ds-solucoes-67319',
    storageBucket: 'ds-solucoes-67319.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDew6tXw-HOH5I31sI11Ttfzok3p6xwgMw',
    appId: '1:321468437653:ios:72f5b48d0cfff37eefb79c',
    messagingSenderId: '321468437653',
    projectId: 'ds-solucoes-67319',
    storageBucket: 'ds-solucoes-67319.firebasestorage.app',
    iosBundleId: 'com.example.dsSolucoes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDew6tXw-HOH5I31sI11Ttfzok3p6xwgMw',
    appId: '1:321468437653:ios:72f5b48d0cfff37eefb79c',
    messagingSenderId: '321468437653',
    projectId: 'ds-solucoes-67319',
    storageBucket: 'ds-solucoes-67319.firebasestorage.app',
    iosBundleId: 'com.example.dsSolucoes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD50RuW_UvWawBcWYusCVS4_nGwwlZpnME',
    appId: '1:321468437653:web:a1a82cfd2bad5c90efb79c',
    messagingSenderId: '321468437653',
    projectId: 'ds-solucoes-67319',
    authDomain: 'ds-solucoes-67319.firebaseapp.com',
    storageBucket: 'ds-solucoes-67319.firebasestorage.app',
  );
}
